using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class Availability_Model
{
    [RealtimeProperty(1, true, true)]
    bool _available = true;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class Availability_Model : RealtimeModel {
    public bool available {
        get {
            return _cache.LookForValueInCache(_available, entry => entry.availableSet, entry => entry.available);
        }
        set {
            if (this.available == value) return;
            _cache.UpdateLocalCache(entry => { entry.availableSet = true; entry.available = value; return entry; });
            InvalidateReliableLength();
            FireAvailableDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(Availability_Model model, T value);
    public event PropertyChangedHandler<bool> availableDidChange;
    
    private struct LocalCacheEntry {
        public bool availableSet;
        public bool available;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        Available = 1,
    }
    
    public Availability_Model() : this(null) {
    }
    
    public Availability_Model(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireAvailableDidChange(bool value) {
        try {
            availableDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.Available, _available ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.availableSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.Available, entry.available ? 1u : 0u);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.Available, _available ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.availableSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.availableSet) {
                stream.WriteVarint32((uint)PropertyID.Available, entry.available ? 1u : 0u);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Available: {
                    bool previousValue = _available;
                    _available = (stream.ReadVarint32() != 0);
                    bool availableExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.availableSet);
                    if (!availableExistsInChangeCache && _available != previousValue) {
                        FireAvailableDidChange(_available);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _available = available;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
