using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class TeamCreationPod_Model
{
    [RealtimeProperty(1, true, true)]
    int _clientDoneDisablingNonTeamGameplayObjects;

    [RealtimeProperty(2, true, true)]
    bool _index0DoneFiltering;

    [RealtimeProperty(3, true, true)]
    bool _index1DoneFiltering;

    [RealtimeProperty(4, true, true)]
    bool _index2DoneFiltering;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class TeamCreationPod_Model : RealtimeModel {
    public int clientDoneDisablingNonTeamGameplayObjects {
        get {
            return _cache.LookForValueInCache(_clientDoneDisablingNonTeamGameplayObjects, entry => entry.clientDoneDisablingNonTeamGameplayObjectsSet, entry => entry.clientDoneDisablingNonTeamGameplayObjects);
        }
        set {
            if (this.clientDoneDisablingNonTeamGameplayObjects == value) return;
            _cache.UpdateLocalCache(entry => { entry.clientDoneDisablingNonTeamGameplayObjectsSet = true; entry.clientDoneDisablingNonTeamGameplayObjects = value; return entry; });
            InvalidateReliableLength();
            FireClientDoneDisablingNonTeamGameplayObjectsDidChange(value);
        }
    }
    
    public bool index0DoneFiltering {
        get {
            return _cache.LookForValueInCache(_index0DoneFiltering, entry => entry.index0DoneFilteringSet, entry => entry.index0DoneFiltering);
        }
        set {
            if (this.index0DoneFiltering == value) return;
            _cache.UpdateLocalCache(entry => { entry.index0DoneFilteringSet = true; entry.index0DoneFiltering = value; return entry; });
            InvalidateReliableLength();
            FireIndex0DoneFilteringDidChange(value);
        }
    }
    
    public bool index1DoneFiltering {
        get {
            return _cache.LookForValueInCache(_index1DoneFiltering, entry => entry.index1DoneFilteringSet, entry => entry.index1DoneFiltering);
        }
        set {
            if (this.index1DoneFiltering == value) return;
            _cache.UpdateLocalCache(entry => { entry.index1DoneFilteringSet = true; entry.index1DoneFiltering = value; return entry; });
            InvalidateReliableLength();
            FireIndex1DoneFilteringDidChange(value);
        }
    }
    
    public bool index2DoneFiltering {
        get {
            return _cache.LookForValueInCache(_index2DoneFiltering, entry => entry.index2DoneFilteringSet, entry => entry.index2DoneFiltering);
        }
        set {
            if (this.index2DoneFiltering == value) return;
            _cache.UpdateLocalCache(entry => { entry.index2DoneFilteringSet = true; entry.index2DoneFiltering = value; return entry; });
            InvalidateReliableLength();
            FireIndex2DoneFilteringDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(TeamCreationPod_Model model, T value);
    public event PropertyChangedHandler<int> clientDoneDisablingNonTeamGameplayObjectsDidChange;
    public event PropertyChangedHandler<bool> index0DoneFilteringDidChange;
    public event PropertyChangedHandler<bool> index1DoneFilteringDidChange;
    public event PropertyChangedHandler<bool> index2DoneFilteringDidChange;
    
    private struct LocalCacheEntry {
        public bool clientDoneDisablingNonTeamGameplayObjectsSet;
        public int clientDoneDisablingNonTeamGameplayObjects;
        public bool index0DoneFilteringSet;
        public bool index0DoneFiltering;
        public bool index1DoneFilteringSet;
        public bool index1DoneFiltering;
        public bool index2DoneFilteringSet;
        public bool index2DoneFiltering;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        ClientDoneDisablingNonTeamGameplayObjects = 1,
        Index0DoneFiltering = 2,
        Index1DoneFiltering = 3,
        Index2DoneFiltering = 4,
    }
    
    public TeamCreationPod_Model() : this(null) {
    }
    
    public TeamCreationPod_Model(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireClientDoneDisablingNonTeamGameplayObjectsDidChange(int value) {
        try {
            clientDoneDisablingNonTeamGameplayObjectsDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireIndex0DoneFilteringDidChange(bool value) {
        try {
            index0DoneFilteringDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireIndex1DoneFilteringDidChange(bool value) {
        try {
            index1DoneFilteringDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireIndex2DoneFilteringDidChange(bool value) {
        try {
            index2DoneFilteringDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.ClientDoneDisablingNonTeamGameplayObjects, (uint)_clientDoneDisablingNonTeamGameplayObjects);
            length += WriteStream.WriteVarint32Length((uint)PropertyID.Index0DoneFiltering, _index0DoneFiltering ? 1u : 0u);
            length += WriteStream.WriteVarint32Length((uint)PropertyID.Index1DoneFiltering, _index1DoneFiltering ? 1u : 0u);
            length += WriteStream.WriteVarint32Length((uint)PropertyID.Index2DoneFiltering, _index2DoneFiltering ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.clientDoneDisablingNonTeamGameplayObjectsSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.ClientDoneDisablingNonTeamGameplayObjects, (uint)entry.clientDoneDisablingNonTeamGameplayObjects);
            }
            if (entry.index0DoneFilteringSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.Index0DoneFiltering, entry.index0DoneFiltering ? 1u : 0u);
            }
            if (entry.index1DoneFilteringSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.Index1DoneFiltering, entry.index1DoneFiltering ? 1u : 0u);
            }
            if (entry.index2DoneFilteringSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.Index2DoneFiltering, entry.index2DoneFiltering ? 1u : 0u);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.ClientDoneDisablingNonTeamGameplayObjects, (uint)_clientDoneDisablingNonTeamGameplayObjects);
            stream.WriteVarint32((uint)PropertyID.Index0DoneFiltering, _index0DoneFiltering ? 1u : 0u);
            stream.WriteVarint32((uint)PropertyID.Index1DoneFiltering, _index1DoneFiltering ? 1u : 0u);
            stream.WriteVarint32((uint)PropertyID.Index2DoneFiltering, _index2DoneFiltering ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.clientDoneDisablingNonTeamGameplayObjectsSet || entry.index0DoneFilteringSet || entry.index1DoneFilteringSet || entry.index2DoneFilteringSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.clientDoneDisablingNonTeamGameplayObjectsSet) {
                stream.WriteVarint32((uint)PropertyID.ClientDoneDisablingNonTeamGameplayObjects, (uint)entry.clientDoneDisablingNonTeamGameplayObjects);
                didWriteProperties = true;
            }
            if (entry.index0DoneFilteringSet) {
                stream.WriteVarint32((uint)PropertyID.Index0DoneFiltering, entry.index0DoneFiltering ? 1u : 0u);
                didWriteProperties = true;
            }
            if (entry.index1DoneFilteringSet) {
                stream.WriteVarint32((uint)PropertyID.Index1DoneFiltering, entry.index1DoneFiltering ? 1u : 0u);
                didWriteProperties = true;
            }
            if (entry.index2DoneFilteringSet) {
                stream.WriteVarint32((uint)PropertyID.Index2DoneFiltering, entry.index2DoneFiltering ? 1u : 0u);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.ClientDoneDisablingNonTeamGameplayObjects: {
                    int previousValue = _clientDoneDisablingNonTeamGameplayObjects;
                    _clientDoneDisablingNonTeamGameplayObjects = (int)stream.ReadVarint32();
                    bool clientDoneDisablingNonTeamGameplayObjectsExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.clientDoneDisablingNonTeamGameplayObjectsSet);
                    if (!clientDoneDisablingNonTeamGameplayObjectsExistsInChangeCache && _clientDoneDisablingNonTeamGameplayObjects != previousValue) {
                        FireClientDoneDisablingNonTeamGameplayObjectsDidChange(_clientDoneDisablingNonTeamGameplayObjects);
                    }
                    break;
                }
                case (uint)PropertyID.Index0DoneFiltering: {
                    bool previousValue = _index0DoneFiltering;
                    _index0DoneFiltering = (stream.ReadVarint32() != 0);
                    bool index0DoneFilteringExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.index0DoneFilteringSet);
                    if (!index0DoneFilteringExistsInChangeCache && _index0DoneFiltering != previousValue) {
                        FireIndex0DoneFilteringDidChange(_index0DoneFiltering);
                    }
                    break;
                }
                case (uint)PropertyID.Index1DoneFiltering: {
                    bool previousValue = _index1DoneFiltering;
                    _index1DoneFiltering = (stream.ReadVarint32() != 0);
                    bool index1DoneFilteringExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.index1DoneFilteringSet);
                    if (!index1DoneFilteringExistsInChangeCache && _index1DoneFiltering != previousValue) {
                        FireIndex1DoneFilteringDidChange(_index1DoneFiltering);
                    }
                    break;
                }
                case (uint)PropertyID.Index2DoneFiltering: {
                    bool previousValue = _index2DoneFiltering;
                    _index2DoneFiltering = (stream.ReadVarint32() != 0);
                    bool index2DoneFilteringExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.index2DoneFilteringSet);
                    if (!index2DoneFilteringExistsInChangeCache && _index2DoneFiltering != previousValue) {
                        FireIndex2DoneFilteringDidChange(_index2DoneFiltering);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _clientDoneDisablingNonTeamGameplayObjects = clientDoneDisablingNonTeamGameplayObjects;
        _index0DoneFiltering = index0DoneFiltering;
        _index1DoneFiltering = index1DoneFiltering;
        _index2DoneFiltering = index2DoneFiltering;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
