using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class PlayerSync_Model
{
    [RealtimeProperty(1, true, true)]
    string _playerName;

    [RealtimeProperty(2, true, true)]
    int _playerHeadIndex;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class PlayerSync_Model : RealtimeModel {
    public string playerName {
        get {
            return _cache.LookForValueInCache(_playerName, entry => entry.playerNameSet, entry => entry.playerName);
        }
        set {
            if (this.playerName == value) return;
            _cache.UpdateLocalCache(entry => { entry.playerNameSet = true; entry.playerName = value; return entry; });
            InvalidateReliableLength();
            FirePlayerNameDidChange(value);
        }
    }
    
    public int playerHeadIndex {
        get {
            return _cache.LookForValueInCache(_playerHeadIndex, entry => entry.playerHeadIndexSet, entry => entry.playerHeadIndex);
        }
        set {
            if (this.playerHeadIndex == value) return;
            _cache.UpdateLocalCache(entry => { entry.playerHeadIndexSet = true; entry.playerHeadIndex = value; return entry; });
            InvalidateReliableLength();
            FirePlayerHeadIndexDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(PlayerSync_Model model, T value);
    public event PropertyChangedHandler<string> playerNameDidChange;
    public event PropertyChangedHandler<int> playerHeadIndexDidChange;
    
    private struct LocalCacheEntry {
        public bool playerNameSet;
        public string playerName;
        public bool playerHeadIndexSet;
        public int playerHeadIndex;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        PlayerName = 1,
        PlayerHeadIndex = 2,
    }
    
    public PlayerSync_Model() : this(null) {
    }
    
    public PlayerSync_Model(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FirePlayerNameDidChange(string value) {
        try {
            playerNameDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FirePlayerHeadIndexDidChange(int value) {
        try {
            playerHeadIndexDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteStringLength((uint)PropertyID.PlayerName, _playerName);
            length += WriteStream.WriteVarint32Length((uint)PropertyID.PlayerHeadIndex, (uint)_playerHeadIndex);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.playerNameSet) {
                length += WriteStream.WriteStringLength((uint)PropertyID.PlayerName, entry.playerName);
            }
            if (entry.playerHeadIndexSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.PlayerHeadIndex, (uint)entry.playerHeadIndex);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteString((uint)PropertyID.PlayerName, _playerName);
            stream.WriteVarint32((uint)PropertyID.PlayerHeadIndex, (uint)_playerHeadIndex);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.playerNameSet || entry.playerHeadIndexSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.playerNameSet) {
                stream.WriteString((uint)PropertyID.PlayerName, entry.playerName);
                didWriteProperties = true;
            }
            if (entry.playerHeadIndexSet) {
                stream.WriteVarint32((uint)PropertyID.PlayerHeadIndex, (uint)entry.playerHeadIndex);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.PlayerName: {
                    string previousValue = _playerName;
                    _playerName = stream.ReadString();
                    bool playerNameExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.playerNameSet);
                    if (!playerNameExistsInChangeCache && _playerName != previousValue) {
                        FirePlayerNameDidChange(_playerName);
                    }
                    break;
                }
                case (uint)PropertyID.PlayerHeadIndex: {
                    int previousValue = _playerHeadIndex;
                    _playerHeadIndex = (int)stream.ReadVarint32();
                    bool playerHeadIndexExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.playerHeadIndexSet);
                    if (!playerHeadIndexExistsInChangeCache && _playerHeadIndex != previousValue) {
                        FirePlayerHeadIndexDidChange(_playerHeadIndex);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _playerName = playerName;
        _playerHeadIndex = playerHeadIndex;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
