using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class DysonSpherePiece_Model
{
    [RealtimeProperty(1, true, true)]
    bool _connectedToStar;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class DysonSpherePiece_Model : RealtimeModel {
    public bool connectedToStar {
        get {
            return _cache.LookForValueInCache(_connectedToStar, entry => entry.connectedToStarSet, entry => entry.connectedToStar);
        }
        set {
            if (this.connectedToStar == value) return;
            _cache.UpdateLocalCache(entry => { entry.connectedToStarSet = true; entry.connectedToStar = value; return entry; });
            InvalidateReliableLength();
            FireConnectedToStarDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(DysonSpherePiece_Model model, T value);
    public event PropertyChangedHandler<bool> connectedToStarDidChange;
    
    private struct LocalCacheEntry {
        public bool connectedToStarSet;
        public bool connectedToStar;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        ConnectedToStar = 1,
    }
    
    public DysonSpherePiece_Model() : this(null) {
    }
    
    public DysonSpherePiece_Model(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireConnectedToStarDidChange(bool value) {
        try {
            connectedToStarDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.ConnectedToStar, _connectedToStar ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.connectedToStarSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.ConnectedToStar, entry.connectedToStar ? 1u : 0u);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.ConnectedToStar, _connectedToStar ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.connectedToStarSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.connectedToStarSet) {
                stream.WriteVarint32((uint)PropertyID.ConnectedToStar, entry.connectedToStar ? 1u : 0u);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.ConnectedToStar: {
                    bool previousValue = _connectedToStar;
                    _connectedToStar = (stream.ReadVarint32() != 0);
                    bool connectedToStarExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.connectedToStarSet);
                    if (!connectedToStarExistsInChangeCache && _connectedToStar != previousValue) {
                        FireConnectedToStarDidChange(_connectedToStar);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _connectedToStar = connectedToStar;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
