using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class InteractiveScreenSync_Model
{
    [RealtimeProperty(1, true, true)]
    bool _executingAnything = false;

    [RealtimeProperty(2, true, true)]
    bool _executingMinMax = false;

    [RealtimeProperty(3, true, true)]
    bool _executingSlideChange = false;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class InteractiveScreenSync_Model : RealtimeModel {
    public bool executingAnything {
        get {
            return _cache.LookForValueInCache(_executingAnything, entry => entry.executingAnythingSet, entry => entry.executingAnything);
        }
        set {
            if (this.executingAnything == value) return;
            _cache.UpdateLocalCache(entry => { entry.executingAnythingSet = true; entry.executingAnything = value; return entry; });
            InvalidateReliableLength();
            FireExecutingAnythingDidChange(value);
        }
    }
    
    public bool executingMinMax {
        get {
            return _cache.LookForValueInCache(_executingMinMax, entry => entry.executingMinMaxSet, entry => entry.executingMinMax);
        }
        set {
            if (this.executingMinMax == value) return;
            _cache.UpdateLocalCache(entry => { entry.executingMinMaxSet = true; entry.executingMinMax = value; return entry; });
            InvalidateReliableLength();
            FireExecutingMinMaxDidChange(value);
        }
    }
    
    public bool executingSlideChange {
        get {
            return _cache.LookForValueInCache(_executingSlideChange, entry => entry.executingSlideChangeSet, entry => entry.executingSlideChange);
        }
        set {
            if (this.executingSlideChange == value) return;
            _cache.UpdateLocalCache(entry => { entry.executingSlideChangeSet = true; entry.executingSlideChange = value; return entry; });
            InvalidateReliableLength();
            FireExecutingSlideChangeDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(InteractiveScreenSync_Model model, T value);
    public event PropertyChangedHandler<bool> executingAnythingDidChange;
    public event PropertyChangedHandler<bool> executingMinMaxDidChange;
    public event PropertyChangedHandler<bool> executingSlideChangeDidChange;
    
    private struct LocalCacheEntry {
        public bool executingAnythingSet;
        public bool executingAnything;
        public bool executingMinMaxSet;
        public bool executingMinMax;
        public bool executingSlideChangeSet;
        public bool executingSlideChange;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        ExecutingAnything = 1,
        ExecutingMinMax = 2,
        ExecutingSlideChange = 3,
    }
    
    public InteractiveScreenSync_Model() : this(null) {
    }
    
    public InteractiveScreenSync_Model(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireExecutingAnythingDidChange(bool value) {
        try {
            executingAnythingDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireExecutingMinMaxDidChange(bool value) {
        try {
            executingMinMaxDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireExecutingSlideChangeDidChange(bool value) {
        try {
            executingSlideChangeDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.ExecutingAnything, _executingAnything ? 1u : 0u);
            length += WriteStream.WriteVarint32Length((uint)PropertyID.ExecutingMinMax, _executingMinMax ? 1u : 0u);
            length += WriteStream.WriteVarint32Length((uint)PropertyID.ExecutingSlideChange, _executingSlideChange ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.executingAnythingSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.ExecutingAnything, entry.executingAnything ? 1u : 0u);
            }
            if (entry.executingMinMaxSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.ExecutingMinMax, entry.executingMinMax ? 1u : 0u);
            }
            if (entry.executingSlideChangeSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.ExecutingSlideChange, entry.executingSlideChange ? 1u : 0u);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.ExecutingAnything, _executingAnything ? 1u : 0u);
            stream.WriteVarint32((uint)PropertyID.ExecutingMinMax, _executingMinMax ? 1u : 0u);
            stream.WriteVarint32((uint)PropertyID.ExecutingSlideChange, _executingSlideChange ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.executingAnythingSet || entry.executingMinMaxSet || entry.executingSlideChangeSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.executingAnythingSet) {
                stream.WriteVarint32((uint)PropertyID.ExecutingAnything, entry.executingAnything ? 1u : 0u);
                didWriteProperties = true;
            }
            if (entry.executingMinMaxSet) {
                stream.WriteVarint32((uint)PropertyID.ExecutingMinMax, entry.executingMinMax ? 1u : 0u);
                didWriteProperties = true;
            }
            if (entry.executingSlideChangeSet) {
                stream.WriteVarint32((uint)PropertyID.ExecutingSlideChange, entry.executingSlideChange ? 1u : 0u);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.ExecutingAnything: {
                    bool previousValue = _executingAnything;
                    _executingAnything = (stream.ReadVarint32() != 0);
                    bool executingAnythingExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.executingAnythingSet);
                    if (!executingAnythingExistsInChangeCache && _executingAnything != previousValue) {
                        FireExecutingAnythingDidChange(_executingAnything);
                    }
                    break;
                }
                case (uint)PropertyID.ExecutingMinMax: {
                    bool previousValue = _executingMinMax;
                    _executingMinMax = (stream.ReadVarint32() != 0);
                    bool executingMinMaxExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.executingMinMaxSet);
                    if (!executingMinMaxExistsInChangeCache && _executingMinMax != previousValue) {
                        FireExecutingMinMaxDidChange(_executingMinMax);
                    }
                    break;
                }
                case (uint)PropertyID.ExecutingSlideChange: {
                    bool previousValue = _executingSlideChange;
                    _executingSlideChange = (stream.ReadVarint32() != 0);
                    bool executingSlideChangeExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.executingSlideChangeSet);
                    if (!executingSlideChangeExistsInChangeCache && _executingSlideChange != previousValue) {
                        FireExecutingSlideChangeDidChange(_executingSlideChange);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _executingAnything = executingAnything;
        _executingMinMax = executingMinMax;
        _executingSlideChange = executingSlideChange;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
