using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class GameManagerSync_Model
{
    [RealtimeProperty(1, true, true)]
    int _clientsDoneSpawning;

    [RealtimeProperty(2, true, true)]
    int _clientCrossedFinishLine;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class GameManagerSync_Model : RealtimeModel {
    public int clientsDoneSpawning {
        get {
            return _cache.LookForValueInCache(_clientsDoneSpawning, entry => entry.clientsDoneSpawningSet, entry => entry.clientsDoneSpawning);
        }
        set {
            if (this.clientsDoneSpawning == value) return;
            _cache.UpdateLocalCache(entry => { entry.clientsDoneSpawningSet = true; entry.clientsDoneSpawning = value; return entry; });
            InvalidateReliableLength();
            FireClientsDoneSpawningDidChange(value);
        }
    }
    
    public int clientCrossedFinishLine {
        get {
            return _cache.LookForValueInCache(_clientCrossedFinishLine, entry => entry.clientCrossedFinishLineSet, entry => entry.clientCrossedFinishLine);
        }
        set {
            if (this.clientCrossedFinishLine == value) return;
            _cache.UpdateLocalCache(entry => { entry.clientCrossedFinishLineSet = true; entry.clientCrossedFinishLine = value; return entry; });
            InvalidateReliableLength();
            FireClientCrossedFinishLineDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(GameManagerSync_Model model, T value);
    public event PropertyChangedHandler<int> clientsDoneSpawningDidChange;
    public event PropertyChangedHandler<int> clientCrossedFinishLineDidChange;
    
    private struct LocalCacheEntry {
        public bool clientsDoneSpawningSet;
        public int clientsDoneSpawning;
        public bool clientCrossedFinishLineSet;
        public int clientCrossedFinishLine;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        ClientsDoneSpawning = 1,
        ClientCrossedFinishLine = 2,
    }
    
    public GameManagerSync_Model() : this(null) {
    }
    
    public GameManagerSync_Model(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireClientsDoneSpawningDidChange(int value) {
        try {
            clientsDoneSpawningDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireClientCrossedFinishLineDidChange(int value) {
        try {
            clientCrossedFinishLineDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.ClientsDoneSpawning, (uint)_clientsDoneSpawning);
            length += WriteStream.WriteVarint32Length((uint)PropertyID.ClientCrossedFinishLine, (uint)_clientCrossedFinishLine);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.clientsDoneSpawningSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.ClientsDoneSpawning, (uint)entry.clientsDoneSpawning);
            }
            if (entry.clientCrossedFinishLineSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.ClientCrossedFinishLine, (uint)entry.clientCrossedFinishLine);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.ClientsDoneSpawning, (uint)_clientsDoneSpawning);
            stream.WriteVarint32((uint)PropertyID.ClientCrossedFinishLine, (uint)_clientCrossedFinishLine);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.clientsDoneSpawningSet || entry.clientCrossedFinishLineSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.clientsDoneSpawningSet) {
                stream.WriteVarint32((uint)PropertyID.ClientsDoneSpawning, (uint)entry.clientsDoneSpawning);
                didWriteProperties = true;
            }
            if (entry.clientCrossedFinishLineSet) {
                stream.WriteVarint32((uint)PropertyID.ClientCrossedFinishLine, (uint)entry.clientCrossedFinishLine);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.ClientsDoneSpawning: {
                    int previousValue = _clientsDoneSpawning;
                    _clientsDoneSpawning = (int)stream.ReadVarint32();
                    bool clientsDoneSpawningExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.clientsDoneSpawningSet);
                    if (!clientsDoneSpawningExistsInChangeCache && _clientsDoneSpawning != previousValue) {
                        FireClientsDoneSpawningDidChange(_clientsDoneSpawning);
                    }
                    break;
                }
                case (uint)PropertyID.ClientCrossedFinishLine: {
                    int previousValue = _clientCrossedFinishLine;
                    _clientCrossedFinishLine = (int)stream.ReadVarint32();
                    bool clientCrossedFinishLineExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.clientCrossedFinishLineSet);
                    if (!clientCrossedFinishLineExistsInChangeCache && _clientCrossedFinishLine != previousValue) {
                        FireClientCrossedFinishLineDidChange(_clientCrossedFinishLine);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _clientsDoneSpawning = clientsDoneSpawning;
        _clientCrossedFinishLine = clientCrossedFinishLine;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
